export const QUOTE_PENDING = 'QUOTE_PENDING';
export const QUOTE_READY = 'QUOTE_READY';
export const QUOTE_REFUSED = 'QUOTE_REFUSED';
export const QUOTE_ACCEPTED = 'QUOTE_ACCEPTED';
export const READY_FOR_PRODUCTION = 'READY_FOR_PRODUCTION';
export const IN_PRODUCTION = 'IN_PRODUCTION';
export const SHIPPED = 'SHIPPED';
export const COMPLETED = 'COMPLETED';
